AtualizaEventoMagazineLuiza/Models/ErrorViewModel.cs
using System;

namespace AtualizaEventoMagazineLuiza.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AtualizaEventoMagazineLuiza/Models/MontarRelatorios.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AtualizaEventoMagazineLuiza.Models
{
    public class MontarRelatorios
    {
        public int IdRemetente { get; set; }
        public int IdUnidadePostadora { get; set; }
        public int StFormatoRetorno { get; set; }
        public DateTime DtInicial { get; set; }
        public DateTime DtFinal { get; set; }

        public MontarRelatorios()
        {
            IdRemetente = 24419;
            StFormatoRetorno = 10015;
        }

    }
}

AtualizaEventoMagazineLuiza/Models/Pedidos.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AtualizaEventoMagazineLuiza.Models
{
    public class Pedidos
    {
        public int Id { get; set; }
        public int Pedido { get; set; }

        public int NotaFiscal { get; set; }

        public string Etiqueta { get; set; }

        public int StatusEvento { get; set; }

        public DateTime DataOcorrencia { get; set; }
        public Pedidos()
        {
            Id = int.MinValue;
            Pedido = int.MinValue;
            NotaFiscal = int.MinValue;
            Etiqueta = string.Empty;
            StatusEvento = int.MinValue;
            DataOcorrencia = DateTime.MinValue;
        }
    }

    
}

AtualizaEventoMagazineLuiza/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AtualizaEventoMagazineLuiza.Models;

namespace AtualizaEventoMagazineLuiza.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AtualizaEventoMagazineLuiza/Controllers/MontarRelatoriosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AtualizaEventoMagazineLuiza.Models;
using System.IO;
using AtualizaEventoMagazineLuiza.Data;

namespace AtualizaEventoMagazineLuiza.Controllers
{
    public class MontarRelatoriosController : Controller
    {
        public async Task<IActionResult> Index()
        {
            ViewData["DtInicial"] = DateTime.Now.ToString("yyyy-MM-ddT00:01");
            ViewData["DtFinal"] = DateTime.Now.ToString("yyyy-MM-ddT23:59");
            return View();
        }

        [HttpPost]
        public FileStreamResult Stream(MontarRelatorios montarRelatorios)
        {
            var fileContent = MagazineLuizaData.MontaArquivoRetorno(montarRelatorios);
            if (fileContent.Length > 1)
            {
                var stream = new MemoryStream(fileContent);
                var fileStreamResult = new FileStreamResult(stream, contentType: "text/csv");
                fileStreamResult.FileDownloadName = "ManuseioMagazineLuzia.csv";
                return fileStreamResult;
            }
            return null;
        }

    }
}

AtualizaEventoMagazineLuiza/Controllers/PedidosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AtualizaEventoMagazineLuiza.Models;
using AtualizaEventoMagazineLuiza.Data;

namespace AtualizaEventoMagazineLuiza.Controllers
{
    public class PedidosController : Controller
    {
        public IActionResult Index(Pedidos Opedido)
        {
            if (Opedido.Pedido != 0)
            {
                try
                {
                    Opedido = MagazineLuizaData.BuscaEtiqueta(Opedido.Pedido);
                    ViewData["Etiqueta"] = Opedido.Etiqueta;
                    ViewData["Pedido"] = Opedido.Pedido;
                    ViewData["DataOcorrencia"] = Opedido.DataOcorrencia.ToString("yyy-MM-ddTHH:mm");
                    if (Opedido != null)
                    {
                        MagazineLuizaData.EnviaPedidos(Opedido);
                    }
                    else
                    {
                        ViewData["Info"] = "Objeto não localizado";
                    }
                }
                catch
                {
                    ViewData["Info"] = "Objeto não localizado";
                }
            }
            else if (!Opedido.Etiqueta.Equals(string.Empty))
            {
                try
                {
                    Opedido = MagazineLuizaData.BuscaObservacaoUm(Opedido.Etiqueta);
                    ViewData["Etiqueta"] = Opedido.Etiqueta;
                    ViewData["Pedido"] = Opedido.Pedido;
                    ViewData["DataOcorrencia"] = Opedido.DataOcorrencia.ToString("yyy-MM-ddTHH:mm");
                    if (Opedido != null)
                    {
                        MagazineLuizaData.EnviaPedidos(Opedido);
                    }
                    else
                    {
                        ViewData["Info"] = "Objeto não localizado";
                    }
                }
                catch
                {
                    ViewData["Info"] = "Objeto não localizado";
                }
            }
            else
            {
                ViewData["DataOcorrencia"] = DateTime.Now.ToString("yyyy-MM-ddTHH:mm");
            }

            return View(Opedido);
        }

        [HttpPost]
        public string BuscarEtiqueta(string p)
        {
            try
            {
                Pedidos oPedido = MagazineLuizaData.BuscaEtiqueta(int.Parse(p));
                return oPedido.Etiqueta;
                
            }
            catch (NullReferenceException)
            {
                return "Objeto não encontrado";
            }
            catch (ArgumentNullException)
            {
                return null;
            }
        }

        [HttpPost]
        public string BuscarPedido(string p)
        {
            try
            {
                Pedidos oPedido = MagazineLuizaData.BuscaObservacaoUm(p);
                return oPedido.Pedido.ToString();

            }
            catch (NullReferenceException)
            {
                return "Objeto não encontrado";
            }
            catch (ArgumentNullException)
            {
                return null;
            }
        }
    }
}

AtualizaEventoMagazineLuiza/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

AtualizaEventoMagazineLuiza/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<link href="css/bootstrap.min.css" rel="stylesheet">
<link href="ADM/plugins/jQueryUI/jquery-ui.min.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<link href="css/animate.min.css" rel="stylesheet">
<link href="css/owl.carousel.css" rel="stylesheet">
<link href="css/owl.transitions.css" rel="stylesheet">
<link href="css/prettyPhoto.css" rel="stylesheet">
<link href="css/main.css" rel="stylesheet">
<link href="css/responsive.css" rel="stylesheet">
<link href="css/star-rating.min.css" rel="stylesheet">

AtualizaEventoMagazineLuiza/Views/MontarRelatorios/Index.cshtml
@model AtualizaEventoMagazineLuiza.Models.MontarRelatorios

@{
    ViewData["Title"] = "Montar Relatorio de Manuseio";
}

<head>
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link href="css/animate.min.css" rel="stylesheet">
    <link href="css/owl.carousel.css" rel="stylesheet">
    <link href="css/owl.transitions.css" rel="stylesheet">
    <link href="css/prettyPhoto.css" rel="stylesheet">
    <link href="css/main.css" rel="stylesheet">
    <link href="css/responsive.css" rel="stylesheet">
    <link href="css/star-rating.min.css" rel="stylesheet">
    <script type="text/javascript" src="~/js/jquery-3.5.1.min.js"></script>
</head>
<h2>Relatorio de Manuseio</h2>
<hr />
<div class="row">
    <div class="col-md-4">

        <form asp-action="Stream">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label name="Data" class="control-label">Data da Ocorrencia:</label><br />
                <input type="datetime-local" asp-for="DtInicial"
                       name="DtInicial" value="@ViewData["DtInicial"]"
                       min="2020-01-01T00:00" max="" class="form-control">
            </div>
            <div class="form-group">
                <div class="form-group">
                    <input type="datetime-local" asp-for="DtFinal"
                           name="DtFinal" value="@ViewData["DtFinal"]"
                           min="2020-01-01T00:00" max="" class="form-control">
                </div>
                <div class="form-group">
                    <label asp-for="IdUnidadePostadora" class="control-label">AGF Postadora</label><br />
                    <select asp-for="IdUnidadePostadora" class="form-control">
                        <option value="20908784">AGF Riacho das Pedras - MG</option>
                        <option value="50904639">AGF Siga - RJ</option>

                    </select>
                    <br />
                    <div class="form-group">
                        <input type="submit" value="Extrair" class="btn btn-default" />
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AtualizaEventoMagazineLuiza/Views/Pedidos/Index.cshtml
@model AtualizaEventoMagazineLuiza.Models.Pedidos

@{
    ViewData["Title"] = "Atualizar Eventos Magazine Luiza";
}
<head>
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link href="css/animate.min.css" rel="stylesheet">
    <link href="css/owl.carousel.css" rel="stylesheet">
    <link href="css/owl.transitions.css" rel="stylesheet">
    <link href="css/prettyPhoto.css" rel="stylesheet">
    <link href="css/main.css" rel="stylesheet">
    <link href="css/responsive.css" rel="stylesheet">
    <link href="css/star-rating.min.css" rel="stylesheet">
    <script type="text/javascript" src="~/js/jquery-3.5.1.min.js"></script>
    <script type="text/javascript">
        $(function onload() {
            $("#Pedido").blur(function () {
                var p = $("#Pedido").val();
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("BuscarEtiqueta")',
                    data: { p: p },
                    success: function (data) {
                        $("#Etiqueta").val(data);

                    },
                    error: function (data) {
                        $("#Etiqueta").val("Objeto não encontrado!");
                    }
                }
                )
            });
            $("#Etiqueta").blur(function () {
                var p = $("#Etiqueta").val();
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("BuscarPedido")',
                    data: { p: p },
                    success: function (data) {
                        $("#Pedido").val(data);

                    },
                    error: function (data) {
                        $("#Pedido").val("Objeto não encontrado!");
                    }
                }
                )
            });
        });
    </script>
</head>
<h2>Atualizar Eventos Magazine Luiza</h2>
<hr />
<div class="row">
    <div class="col-md-4">

        <form asp-action="Index">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Pedido" class="control-label">N° do Pedido</label>
                <input asp-for="Pedido" id="Pedido" class="form-control" value="@ViewData["Pedido"]" placeholder="560792540" />
            </div>
            <div class="form-group">
                <label asp-for="Etiqueta" class="control-label"></label>
                <input asp-for="Etiqueta" id="Etiqueta" class="form-control" value="@ViewData["Etiqueta"]" placeholder="OI846194865BR" />
            </div>
            <div class="form-group">
                <label asp-for="StatusEvento" class="control-label">Ocorrencia</label><br />
                <select asp-for="StatusEvento" class="form-control">
                    <option value="3700">Retido Para Fiscalização</option>
                    <option value="3800">Em Devolução ao Postador</option>
                    <option value="3900">Devolvido ao Postador</option>
                </select>

            </div>
            <div class="form-group">
                <label asp-for="DataOcorrencia" class="control-label">Data da Ocorrencia:</label><br />
                <input type="datetime-local" asp-for="DataOcorrencia"
                       name="DataOcorrencia" value="@ViewData["DataOcorrencia"]"
                       min="2020-01-01T00:00" max="" class="form-control">
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Enviar" class="btn btn-default" />
            </div>
        </form>
        <br />
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AtualizaEventoMagazineLuiza/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AtualizaEventoMagazineLuiza</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-Cerulean.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link href="css/bootstrap.min.css" rel="stylesheet">
        <link href="ADM/plugins/jQueryUI/jquery-ui.min.css" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
        <link href="css/animate.min.css" rel="stylesheet">
        <link href="css/owl.carousel.css" rel="stylesheet">
        <link href="css/owl.transitions.css" rel="stylesheet">
        <link href="css/prettyPhoto.css" rel="stylesheet">
        <link href="css/main.css" rel="stylesheet">
        <link href="css/responsive.css" rel="stylesheet">
        <link href="css/star-rating.min.css" rel="stylesheet">
    </environment>



</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Pedidos" asp-action="Index">Atualizar Eventos</a></li>
                    <li><a asp-area="" asp-controller="MontarRelatorios" asp-action="Index">Relatorio de Manuseio</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />

        <footer id="footer">
            <div class="container text-center">
                <div class="row">
                    <div class="col-sm-12">
                        &copy; 2020 VisualSet Tecnologia. Desenhado por <a target="_blank" href="https://www.visualset.com.br" title="Faça Sua Web Page Conosco...">VisualSet Web</a>
                    </div>
                    <div class="col-sm-6">
                        <ul class="social-icons">
                            <li>
                                <a href="https://www.facebook.com/VisualSetTecnologia">
                                    <i class="fa fa-facebook"></i>
                                </a>
                            </li>
                            <li><a href="https://twitter.com/VisualSetTec"><i class="fa fa-twitter"></i></a></li>
                            <li>
                                <a href="https://plus.google.com/u/1/114458230443801717151/">
                                    <i class="fa fa-google-plus"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://www.youtube.com/channel/UClQiOMFtcIrWFKMCqj6NV6w">
                                    <i class="fa fa-youtube"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>

    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>


    @RenderSection("Scripts", required: false)



</body>
</html>